### ISSUE TITLE
The programmer does not work in any of the three modes: UPDI, HV, PCHV!

### ISSUE THREAD

**Issue by P55-rgb** [Dlloydev/jtag2updi#14]
I put together your diagram.
The programmer does not work in any of the three modes: UPDI, HV, PCHV! 
I have an Attiny412 controller
Why did you power the tinyAVR controller from your Arduino Nano ADC?
The ADC pins only work for the input, right?!

**Comment by Dlloydev** [comment]
Pins A0-A5 are setup as digital outputs. Since they originate from the same port and are driven at the same time, they are used as a target power source that can be power-cycled when needed. Pin A6 is an input that is used to sense an overload condition on A0-A5. Pin A7 is an input that senses the Mode.

From the [documentation here](
https://github.com/Dlloydev/jtag2updi/wiki/Arduino-Nano-HV-UPDI-Programmer), there's a small table showing the jumper positions and resulting Mode. 

Just below that, there's another small table showing recommended connections for each Mode. The Nano's 6-pin connector can be used for 5V (steady power) and GND and this might be needed under some conditions ... refer to the last table showing test results (ATtiny412) and suggestions.
